# Generated by Django 4.1 on 2022-08-31 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('idBebida', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('preco', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=255, verbose_name='Telefone')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
            ],
        ),
        migrations.CreateModel(
            name='Fornada',
            fields=[
                ('idFornada', models.IntegerField(primary_key=True, serialize=False)),
                ('numFornada', models.IntegerField()),
                ('qtdPizzas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('idIngrediente', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('preco', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idPedido', models.IntegerField(primary_key=True, serialize=False)),
                ('dataHora', models.DateTimeField()),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('idFornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fornada')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('idPizza', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('precoBase', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('idTamanho', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('desconto', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PizzaPedida',
            fields=[
                ('idPizzaPedida', models.IntegerField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('idPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
                ('idPizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pizza')),
                ('idTamanho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tamanho')),
            ],
        ),
        migrations.CreateModel(
            name='PizzaPedida_has_Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idIngrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingrediente')),
                ('idPizzaPedida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pizza')),
            ],
            options={
                'unique_together': {('idPizzaPedida', 'idIngrediente')},
            },
        ),
        migrations.CreateModel(
            name='BebidaPedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('idBebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bebida')),
                ('idPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
            ],
            options={
                'unique_together': {('idBebida', 'idPedido')},
            },
        ),
    ]
