# Generated by Django 4.1.1 on 2022-09-06 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeBebida', models.CharField(max_length=255, verbose_name='NomeBebida')),
                ('preco', models.FloatField(default=0, verbose_name='Preco')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=255, verbose_name='Telefone')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
            ],
        ),
        migrations.CreateModel(
            name='Pastel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(max_length=255, verbose_name='Sabor')),
                ('preco', models.FloatField(default=0, verbose_name='Preco')),
            ],
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(max_length=255, verbose_name='Tamanho')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHora', models.DateTimeField(auto_now=True, verbose_name='DataHora')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='PastelPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantia', models.IntegerField(default=1, verbose_name='Quantia')),
                ('idPastel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pastel')),
                ('idPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
                ('idTamanho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tamanho')),
            ],
        ),
        migrations.CreateModel(
            name='BebidaPedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantia', models.IntegerField(default=1, verbose_name='Quantia')),
                ('idBebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bebida')),
                ('idPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
            ],
        ),
    ]
