# Generated by Django 4.1 on 2022-09-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pizzapedida_has_ingrediente',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pizzapedida_has_ingrediente',
            name='idIngrediente',
        ),
        migrations.RemoveField(
            model_name='pizzapedida_has_ingrediente',
            name='idPizzaPedida',
        ),
        migrations.DeleteModel(
            name='Ingrediente',
        ),
        migrations.DeleteModel(
            name='PizzaPedida_has_Ingrediente',
        ),
    ]
