# Generated by Django 4.1.1 on 2022-09-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='dataHora',
            field=models.DateTimeField(auto_now_add=True, verbose_name='DataHora'),
        ),
    ]
