# Generated by Django 4.1 on 2022-09-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pedido_datahora'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.AddField(
            model_name='pastel',
            name='ingrediente',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ingrediente'),
        ),
        migrations.AlterField(
            model_name='bebida',
            name='nomeBebida',
            field=models.CharField(blank=True, max_length=255, verbose_name='NomeBebida'),
        ),
        migrations.AlterField(
            model_name='bebida',
            name='preco',
            field=models.FloatField(blank=True, default=0, verbose_name='Preco'),
        ),
        migrations.AlterField(
            model_name='pastel',
            name='preco',
            field=models.FloatField(blank=True, default=0, verbose_name='Preco'),
        ),
        migrations.AlterField(
            model_name='pastel',
            name='sabor',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sabor'),
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='Tamanho',
        ),
    ]
