# Generated by Django 4.1 on 2022-09-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_cliente_pastel_ingrediente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebida',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descricao'),
        ),
    ]
